### ISSUE TITLE
ReporteDeActividad#7-EquipoIrvinf

### ISSUE THREAD

**Issue by Diego047** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-de-irving#3]
[Activididad7_DERS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-de-irving/files/10008073/Activididad7_DERS.pdf)

**Comment by Heidi-19** [comment]
Calificación = 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
